const MUSTACHE_B2B_PREFIX = "mds";

module.exports = {
  source: ["tokens/style-dictionary.json"],
  fileHeader: {
    autoGeneratedFileHeader: "Mustache B2B Design System - Foundation",
  },
  platforms: {
    css: {
      transformGroup: "web",
      buildPath: "build/web/css/",
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: "variables.css",
          format: "css/variables",
        },
      ],
    },
    scss: {
      transformGroup: "web",
      buildPath: "build/web/scss/",
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: "_variables.scss",
          format: "scss/variables",
        },
      ],
    },
    android: {
      transformGroup: "android",
      buildPath: "build/android/",
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: "style_dictionary_colors.xml",
          format: "android/colors",
        },
        {
          destination: "style_dictionary_font_dimens.xml",
          format: "android/fontDimens",
        },
        {
          destination: "style_dictionary_dimens.xml",
          format: "android/dimens",
        },
        {
          destination: "style_dictionary_integers.xml",
          format: "android/integers",
        },
        {
          destination: "style_dictionary_strings.xml",
          format: "android/strings",
        },
      ],
    },
    ios: {
      transformGroup: "ios",
      buildPath: "build/ios/",
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: "StyleDictionarySize.h",
          format: "ios/static.h",
          type: "float",
          className: "StyleDictionarySize",
          filter: {
            attributes: {
              category: "size",
            },
          },
        },
        {
          destination: "StyleDictionarySize.m",
          format: "ios/static.m",
          type: "float",
          className: "StyleDictionarySize",
          filter: {
            attributes: {
              category: "size",
            },
          },
        },
        {
          destination: "StyleDictionaryIcons.h",
          format: "ios/strings.h",
          className: "StyleDictionaryIcons",
          filter: {
            attributes: {
              category: "content",
              type: "icon",
            },
          },
        },
        {
          destination: "StyleDictionaryIcons.m",
          format: "ios/strings.m",
          className: "StyleDictionaryIcons",
          filter: {
            attributes: {
              category: "content",
              type: "icon",
            },
          },
        },
        {
          destination: "StyleDictionaryColor.h",
          format: "ios/colors.h",
          className: "StyleDictionaryColor",
          type: "StyleDictionaryColorName",
          filter: {
            attributes: {
              category: "color",
            },
          },
        },
        {
          destination: "StyleDictionaryColor.m",
          format: "ios/colors.m",
          className: "StyleDictionaryColor",
          type: "StyleDictionaryColorName",
          filter: {
            attributes: {
              category: "color",
            },
          },
        },
        {
          destination: "StyleDictionaryProperties.h",
          format: "ios/singleton.h",
          className: "StyleDictionaryProperties",
        },
        {
          destination: "StyleDictionaryProperties.m",
          format: "ios/singleton.m",
          className: "StyleDictionaryProperties",
        },
      ],
    },
  },
};
