const MUSTACHE_B2B_PREFIX = 'mds';

module.exports = {
  source: ['tokens/style-dictionary.json'],
  fileHeader: {
    autoGeneratedFileHeader: 'Mustache B2B Design System - Foundation',
  },
  platforms: {
    css: {
      transformGroup: 'web',
      buildPath: 'build/web/css/',
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
        },
      ],
    },
    scss: {
      transformGroup: 'web',
      buildPath: 'build/web/scss/',
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: '_variables.scss',
          format: 'scss/variables',
        },
      ],
    },
    js: {
      transformGroup: 'web',
      buildPath: 'build/web/js/',
      prefix: MUSTACHE_B2B_PREFIX,
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/module',
        },
      ],
    },
  },
};
